version: '3.8'

services:
  postgres:
    image: postgres:13.1
    container_name: ecommerce-pg-db-connection
    restart: always
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ecommerce-db
    volumes:
      - ecommerce-db:/data/postgres
    ports:
      - 5433:5432

  adminer:
    image: adminer
    container_name: ecommerce-db-adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  ecommerce-db:
